---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: customcharts-gitrepository
  namespace: custom-nginx
spec:
  interval: 2min
  url: https://github.com/alesbrelih/flux-playground
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
