---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: customcharts
  namespace: custom-nginx
spec:
  interval: 10m0s
  url: https://github.com/alesbrelih/flux-playground
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
