---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: custom-nginx
  namespace: custom-nginx
spec:
  chart:
    spec:
      chart: custom-chart
      sourceRef:
        kind: GitRepository
        name: customcharts-gitrepository
  interval: 2m
