---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  chart:
    spec:
      releaseName: psql
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-postgresql
        namespace: flux-system
  interval: 2m
  values:
    primary:
      persistence:
        enabled: false
